language: python
python:
  - "3.4"

install: 
  -  pip install -r requirements.txt
  -  openssl genrsa -out server.pem 4096

script:
  -  export RPCSERVER_TOKEN=`openssl rand -hex 32`
  -  python automator.py